/*
Simon Restrepo
Vista que trae el calendario de rutas y vuelos para consultar salidas
en un lapso de dos semanas.
*/

CREATE OR REPLACE VIEW FLIGHT_SCHEDULES
AS
SELECT R.ID RUTA_ID, V.ID VUELO_ID, 
    FECHA_ESTIMADA_SALIDA,
    TO_CHAR(I.FECHA_ESTIMADA_SALIDA, 'HH24:MI:SS') HORA_SALIDA,
    TO_CHAR(I.FECHA_ESTIMADA_SALIDA, 'dd/MM/yyyy') FECHA_SALIDA
FROM ITINERARIOS I
    INNER JOIN VUELOS V ON I.VUELO_ID = V.ID
    INNER JOIN RUTAS R ON R.ID = V.RUTA_ID
WHERE   FECHA_ESTIMADA_SALIDA  >= TRUNC (FECHA_ESTIMADA_SALIDA, 'IW')
    AND     FECHA_ESTIMADA_SALIDA  <  TRUNC (FECHA_ESTIMADA_SALIDA,   'IW') + 2;
    
    
/*
    SELECT * 
    FROM FLIGHT_SCHEDULES
    WHERE RUTA_ID = 2;  
*/
    