CREATE SEQUENCE id_empleado
INCREMENT BY 1 
START WITH 1 MINVALUE 1;

CREATE SEQUENCE id_piloto
INCREMENT BY 1 
START WITH 1 MINVALUE 1;

CREATE SEQUENCE id_ciudad
INCREMENT BY 1 
START WITH 2 MINVALUE 1;



CREATE SEQUENCE id_itinerario
INCREMENT BY 1 
START WITH 1 MINVALUE 1;


CREATE SEQUENCE id_tripulante_prog
INCREMENT BY 1 
START WITH 1 MINVALUE 1;

CREATE SEQUENCE id_aeropuerto
INCREMENT BY 1 
START WITH 1 MINVALUE 1;


CREATE SEQUENCE id_ruta
INCREMENT BY 1 
START WITH 1 MINVALUE 1;

CREATE SEQUENCE id_vuelo
INCREMENT BY 1 
START WITH 1 MINVALUE 1;


CREATE SEQUENCE id_check_in
INCREMENT BY 1 
START WITH 1 MINVALUE 1;

CREATE SEQUENCE id_pasajero
INCREMENT BY 1 
START WITH 1 MINVALUE 1;

CREATE SEQUENCE id_avion
INCREMENT BY 1 
START WITH 1 MINVALUE 1;

CREATE SEQUENCE id_log_vuelo
INCREMENT BY 1 
START WITH 1 MINVALUE 1;


-- Adecuaciones del modelo
ALTER TABLE AVIONES
ADD ESTADO VARCHAR(15);

ALTER TABLE AVIONES
ADD CONSTRAINT CK_AVIONES_ESTADO 
CHECK (ESTADO in('Vuelo', 'Tierra', 'Mantenimiento', 'Reparación'));

ALTER TABLE ITINERARIOS
ADD CONSTRAINT CK_ITINERARIOS_ESTADO 
CHECK (ESTADO in('En Vuelo', 'Cancelado', 'Retrasado', 'Confirmado', 'Abordando', 'Programado'));

/*
1) Se desea asignar un avión a un vuelo confirmado, para esto es 
necesario una vista que dado el id de
un vuelo confirmado, busque los aviones que se encuentran en el 
aeropuerto de salida (Utilizando la
hora estimada de llegada a esa ciudad / aeropuerto de otros vuelos) 2 horas antes 
de la fecha estimada de salida. (0.3)
*/


SELECT a.id 
FROM AVIONES A
    CROSS JOIN VUELOS V
WHERE A.ESTADO = 'Tierra'
    AND A.ID NOT IN (SELECT I.AVION_ID
                 FROM ITINERARIOS I
                    INNER JOIN AVIONES A ON A.ID = I.AVION_ID 
                    INNER JOIN VUELOS V ON V.ID = I.VUELO_ID
                    INNER JOIN RUTAS R ON R.ID = V.RUTA_ID)
    AND rowNUM = 1;


/*
INSERT INTO AVIONES(id,matricula,serial,edad,asientos_ejecutivos,asientos_economicos,asientos_estandar)VALUES(id_avion.NEXTVAL,'N764AV','Airbus A320-251N	7887',0,12,138,0);
INSERT INTO AVIONES(id,matricula,serial,edad,asientos_ejecutivos,asientos_economicos,asientos_estandar)VALUES(id_avion.NEXTVAL,'N765AV','Airbus A320-251N	7928',0,12,138,0);
INSERT INTO AVIONES(id,matricula,serial,edad,asientos_ejecutivos,asientos_economicos,asientos_estandar)VALUES(id_avion.NEXTVAL,'N766AV','Airbus A320-251N	8096',0,12,138,0);
INSERT INTO AVIONES(id,matricula,serial,edad,asientos_ejecutivos,asientos_economicos,asientos_estandar)VALUES(id_avion.NEXTVAL,'PR-OBD','Airbus A320-251N	7175',1,12,138,0);
INSERT INTO AVIONES(id,matricula,serial,edad,asientos_ejecutivos,asientos_economicos,asientos_estandar)VALUES(id_avion.NEXTVAL,'PR-OBF','Airbus A320-251N	7323',1,12,138,0);
INSERT INTO AVIONES(id,matricula,serial,edad,asientos_ejecutivos,asientos_economicos,asientos_estandar)VALUES(id_avion.NEXTVAL,'PR-OBH','Airbus A320-251N	7484',1,12,138,0);
INSERT INTO AVIONES(id,matricula,serial,edad,asientos_ejecutivos,asientos_economicos,asientos_estandar)VALUES(id_avion.NEXTVAL,'PR-OBI','Airbus A320-251N	7514',1,12,138,0);
INSERT INTO AVIONES(id,matricula,serial,edad,asientos_ejecutivos,asientos_economicos,asientos_estandar)VALUES(id_avion.NEXTVAL,'PR-OBJ','Airbus A320-251N	7698',0,12,138,0);

INSERT INTO AVIONES VALUES(id_avion.NEXTVAL,'N764AV','Airbus A320-251N	7887',0,'Boeing 737',12,138,0,'Tierra');
INSERT INTO AVIONES VALUES(id_avion.NEXTVAL,'N765AV','Airbus A320-251N	7928',0,'Boeing 737',12,138,0,'Tierra');
INSERT INTO AVIONES VALUES(id_avion.NEXTVAL,'N766AV','Airbus A320-251N	8096',0,'Boeing 737',12,138,0,'Tierra');
INSERT INTO AVIONES VALUES(id_avion.NEXTVAL,'PR-OBD','Airbus A320-251N	7175',1,'Boeing 737',12,138,0,'Tierra');
INSERT INTO AVIONES VALUES(id_avion.NEXTVAL,'PR-OBF','Airbus A320-251N	7323',1,'Boeing 737',12,138,0,'Tierra');
INSERT INTO AVIONES VALUES(id_avion.NEXTVAL,'PR-OBH','Airbus A320-251N	7484',1,'Boeing 737',12,138,0,'Tierra');
INSERT INTO AVIONES VALUES(id_avion.NEXTVAL,'PR-OBI','Airbus A320-251N	7514',1,'Boeing 737',12,138,0,'Tierra');
INSERT INTO AVIONES VALUES(id_avion.NEXTVAL,'PR-OBJ','Airbus A320-251N	7698',0,'Boeing 737',12,138,0,'Tierra');


SELECT *
FROM ITINERARIOS I
    LEFT  JOIN AVIONES A ON A.ID = I.AVION_ID
    INNER JOIN VUELOS V ON V.ID = I.VUELO_ID
    INNER JOIN RUTAS R ON R.ID = V.RUTA_ID
WHERE R.AEROPUERTO_DESTINO_ID = ( SELECT R.AEROPUERTO_ORIGEN_ID
                                  FROM ITINERARIOS I
                                    INNER JOIN VUELOS V ON V.ID = I.VUELO_ID
                                    INNER JOIN RUTAS R ON R.ID = V.RUTA_ID)
    
    
select
    24 * (to_date(to_char(sysdate, 'YYYY-MM-DD hh24:mi'), 'YYYY-MM-DD hh24:mi') - to_date('2018-02- 15:20', 'YYYY-MM-DD hh24:mi')) as diff_hours
from dual;    


    INSERT INTO CIUDADES VALUES (id_ciudad.NEXTVAL, 'MEDELLIN','COLOMBIA');
    INSERT INTO ciudades (id,ciudad,pais) VALUES (id_ciudad.NEXTVAL,'BOGOTA','COLOMBIA');
    
select * from ciudades
select * from AEROPUERTOS
 
    INSERT INTO AEROPUERTOS VALUES (id_aeropuerto.NEXTVAL,'Jose Maria Cordova International Airport','MDE',6.170763,-75.42762, 1);
    INSERT INTO AEROPUERTOS VALUES (id_aeropuerto.NEXTVAL,'El Dorado International Airport','BOG',4.701413 ,-74.144497, 2);
    SELECT * FROM vuelos
    INSERT INTO RUTAS VALUES (id_ruta.NEXTVAL,1,2,427,0.5);
INSERT INTO vuelos  VALUES (id_vuelo.NEXTVAL,'AV17',2,2); 
INSERT INTO vuelos  VALUES (id_vuelo.NEXTVAL,'AV8427',3,2);  
INSERT INTO vuelos  VALUES (id_vuelo.NEXTVAL,'AV8433',4,2);  


insert into ITINERARIOS values (id_itinerario.NEXTVAL, SYSDATE, '15/05/2018',null,'Confirmado',0,0,null,'15/05/2018',null,null,4,null,null);
    
    SELECT * FROM ITINERARIOS
    
    */
    
    -- AVION
    SELECT A.* 
    FROM AVIONES A
    WHERE A.ESTADO = 'Tierra'
        AND A.ID NOT IN (SELECT I.AVION_ID
                         FROM ITINERARIOS I
                            INNER JOIN AVIONES A ON A.ID = I.AVION_ID 
                            INNER JOIN VUELOS V ON V.ID = I.VUELO_ID
                            INNER JOIN RUTAS R ON R.ID = V.RUTA_ID)
        AND rownum = 1;
    
    
    -- PILOTO
    SELECT P.ID
    FROM EMPLEADOS E
        INNER JOIN PILOTOS P ON P.EMPLEADO_ID = E.ID
    WHERE E.ESTADO = 'ACTIVO' 
        AND P.TIPO_CARGO = 'PILOTO'
        AND E.HORAS_DESCANSO > 2
        AND E.CIUDAD_ID = (  SELECT C.ID
                             FROM VUELOS V
                                INNER JOIN RUTAS R ON R.ID = V.RUTA_ID
                                INNER JOIN AEROPUERTOS AE ON R.AEROPUERTO_ORIGEN_ID = AE.ID
                                INNER JOIN CIUDADES C ON AE.CIUDAD_ID = C.ID
                             WHERE V.ID = 4)
        AND ROWNUM = 1;
    
    -- COPILOTO
    SELECT P.ID
    FROM EMPLEADOS E
        INNER JOIN PILOTOS P ON P.EMPLEADO_ID = E.ID
    WHERE E.ESTADO = 'ACTIVO' 
        AND P.TIPO_CARGO = 'COPILOTO'
        AND E.HORAS_DESCANSO > 2
        AND E.CIUDAD_ID = (  SELECT C.ID
                             FROM VUELOS V
                                INNER JOIN RUTAS R ON R.ID = V.RUTA_ID
                                INNER JOIN AEROPUERTOS AE ON R.AEROPUERTO_ORIGEN_ID = AE.ID
                                INNER JOIN CIUDADES C ON AE.CIUDAD_ID = C.ID
                             WHERE V.ID = 4)
        AND ROWNUM = 1;
        
        
        SELECT *
		FROM EMPLEADOS E 
		WHERE E.TIPO_EMPLEADO = 'Tripulante'
            AND E.ESTADO = 'ACTIVO'
            AND E.HORAS_DESCANSO >= 2;
            
            
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Finn','Price',80085832727,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Bo','Todd',79299797029,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Rosalyn','Ortega',95108294889,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Clinton','Scott',1016979631,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Stuart','Hardy',50513611347,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Henry','Hoffman',87910728991,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Petra','Fulton',4349420195,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Aristotle','Giles',46481175016,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Aimee','Pacheco',18938014078,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Zorita','Pope',66693843553,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Kylee','Peck',5171289694,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Rylee','Hawkins',85950799934,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Brianna','Gentry',16837015470,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Heather','Rosales',29824688193,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Halee','Gutierrez',17241339528,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Leonard','Dillard',82816427862,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Latifah','Smith',9964453211,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Joan','Jenkins',16582516687,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Mia','Eaton',18417144489,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Victoria','Hoover',77556197136,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Garth','Pace',60050788092,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Alana','Rush',93811087389,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Zeus','Schwartz',23966350140,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Cecilia','Perez',34281642845,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Myra','Pitts',18530165962,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Kaseem','Velez',74814537566,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Angelica','Hansen',74881022046,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Uriah','Head',6467980915,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Mufutau','Bernard',2687334457,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Virginia','Sloan',7798379045,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Joan','Hood',5554823409,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Oleg','Ewing',78268624032,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Jessica','Snyder',25014555324,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Nora','Pittman',32483735587,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Lara','Cruz',10483734732,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Zelda','Pierce',97064318775,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Zachary','Griffith',3339106185,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Rhonda','Holden',82048421827,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Haley','Ruiz',61665246930,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Amy','Kline',38122546671,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Tarik','Richmond',70788509430,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Giselle','Ortega',32342590616,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Ian','Warner',64946593240,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Garrison','Garrett',70296213510,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Graiden','Vaughan',59500626681,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Vincent','Holman',57480220126,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Dara','White',54527137681,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Kasper','Fuller',85250102840,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Ocean','Roy',43105504153,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Felix','Mcknight',59834946072,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Shellie','Morse',99473221114,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Jolene','Jackson',7513639370,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Meghan','England',11920958617,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Fallon','Beasley',81545022609,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Ciara','George',62468365525,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Ava','Finch',60508904388,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Mannix','Acosta',27896607690,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Wanda','Roman',24659956752,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Aurora','Newman',14005797536,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Hannah','Crosby',54547315303,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Dawn','Harris',50683288543,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Wyatt','Mccullough',3586318190,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Violet','Austin',13956046511,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Quentin','Weaver',17135176836,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Geoffrey','Estes',70448731006,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Amos','Best',81566856943,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Hamilton','Warren',65582030512,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Hope','Hooper',95659860336,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Brody','Peterson',57416980473,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Yuri','Morrow',34478894298,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Madison','Fitzpatrick',87611907190,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Colby','Case',59123956173,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Axel','Solis',51572291709,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Zahir','Byers',71189521722,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Zorita','Mcmahon',91390415139,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Mary','Ward',54945545155,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Katelyn','Gay',88243928141,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Maxine','Jenkins',60638865616,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Cairo','Chandler',88911587242,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Jeanette','Sutton',38832567861,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Geoffrey','Johnson',30444108365,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Kuame','Short',36396731969,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Martina','Chapman',2022688113,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Oren','Frye',94876855652,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Macaulay','Benjamin',60542377568,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Selma','Noble',36896896409,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Kyra','Nelson',54114916752,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Chadwick','Humphrey',70523859508,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Henry','Monroe',43965434382,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Kirk','Kim',51087121907,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Emery','Dodson',32060809991,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Charlotte','Weeks',31748621867,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Byron','Cline',77421413199,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Laura','Mcmahon',91483865074,'Cedula Extranjeria',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Candace','Banks',77103385160,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Faith','Le',98308651897,'Cedula',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Ishmael','Myers',33349023750,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Rogan','Carey',44474066325,'Pasaporte',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Quamar','Hill',45598679484,'DNI',4);
INSERT INTO pasajeros (ID,NOMBRE,APELLIDO,IDENTIFICACION,TIPO_DOCUMENTO,VUELO_ID) VALUES (id_pasajero.NEXTVAL,'Leslie','Molina',64691450433,'DNI',4);
